#include "wled.h"

#ifdef ARDUINO_ARCH_ESP32

// AI: below section was generated by an AI
// Implements BLE Wi-Fi onboarding for WLED on ESP32.
//
// Architecture: BLE and WLED's full stack are MUTUALLY EXCLUSIVE per boot.
//   - No credentials stored → boot into BLE provisioning mode only.
//     NimBLE is initialised; setup() blocks so WLED's initServer()/initIR()
//     never run. Their interrupt handlers conflict with the BT controller's
//     high-priority interrupt handler (hli_c_handler) and cause a panic.
//   - Credentials stored    → boot into normal WLED mode, no BLE stack.
//     NimBLEDevice::init() is never called; the BLE controller is idle.
//
// Re-provisioning flow:
//   Use WLED web UI: Security → Factory Reset (wipes /cfg.json).
//   Next boot detects DEFAULT_CLIENT_SSID → enters BLE provisioning mode.

#include <NimBLEDevice.h>  // NimBLE-Arduino: NimBLEDevice, NimBLEServer, NimBLEService, NimBLECharacteristic
#include <esp_coexist.h>   // esp_coex_preference_set(), esp_coex_prefer_t

// --- Service and Characteristic UUIDs ---
#define BLE_SERVICE_UUID     "12345678-1234-1234-1234-123456789abc"
#define BLE_SSID_CHAR_UUID   "12345678-1234-1234-1234-123456789ab1"
#define BLE_PASS_CHAR_UUID   "12345678-1234-1234-1234-123456789ab2"
#define BLE_STATUS_CHAR_UUID "12345678-1234-1234-1234-123456789ab3"

// --- Tuning constants ---
#define WIFI_ATTEMPT_TIMEOUT_MS 6000  // fail-fast: don't hold radio for 30 s default
#define MAX_RETRIES             3
#define RETRY_DELAYS_MS         {0, 2000, 5000}

// --- Status strings delivered to the app via BLE NOTIFY ---
#define STATUS_CONNECTING     "CONNECTING"
#define STATUS_CONNECTED      "CONNECTED"
#define STATUS_WRONG_PASSWORD "ERR_AUTH"
#define STATUS_SSID_NOT_FOUND "ERR_NO_AP"
#define STATUS_TIMEOUT        "ERR_TIMEOUT"
#define STATUS_READY          "READY"

class BLEOnboardingUsermod : public Usermod {
private:
  NimBLEServer*         pServer     = nullptr;
  NimBLECharacteristic* pSsidChar   = nullptr;
  NimBLECharacteristic* pPassChar   = nullptr;
  NimBLECharacteristic* pStatusChar = nullptr;

  // true only when this boot was started in BLE provisioning mode
  bool bleMode = false;

  enum class State {
    BLE_ADVERTISING, // waiting for the app to write credentials
    WIFI_ATTEMPTING, // trying Wi-Fi; BLE stack still active
    WIFI_CONNECTED,  // success — credentials saved, restart pending
    FAILED           // connection failed; scheduled for retry
  };
  State state = State::BLE_ADVERTISING;

  char pendingSsid[33] = {0};
  char pendingPass[65] = {0};

  unsigned long wifiAttemptStart = 0;
  int           retryCount       = 0;
  const int     retryDelays[3]   = RETRY_DELAYS_MS;
  unsigned long nextRetryAt      = 0;

  volatile bool credentialsReceived = false;

  // -----------------------------------------------------------------------
  // Coexistence helper — switches the radio preference without delay().
  // -----------------------------------------------------------------------
  void setCoexMode(esp_coex_prefer_t mode) {
    esp_coex_preference_set(mode);
  }

  // -----------------------------------------------------------------------
  // Push a status string to the mobile app via BLE NOTIFY.
  // -----------------------------------------------------------------------
  void notifyStatus(const char* status) {
    DEBUG_PRINTF("[BLE_OB] notify: %s\n", status);
    if (pStatusChar) {
      pStatusChar->setValue((uint8_t*)status, strlen(status));
      pStatusChar->notify();
    }
  }

  // -----------------------------------------------------------------------
  // Initialise the BLE GATT server. Called once in setup() when bleMode=true.
  // Three characteristics:
  //   SSID   (WRITE)  — app writes the target network SSID
  //   PASS   (WRITE)  — app writes the password; triggers attempt on receipt
  //   STATUS (NOTIFY) — device pushes ASCII status strings to the app
  // Device name is unique per unit: WLED-XX:XX:XX (last MAC octets).
  // -----------------------------------------------------------------------
  void initBLE() {
    char bleName[24];
    snprintf(bleName, sizeof(bleName), "WLED-%s",
             WiFi.macAddress().substring(9).c_str());
    DEBUG_PRINTF("[BLE_OB] init BLE as \"%s\"\n", bleName);
    NimBLEDevice::init(bleName);

    pServer = NimBLEDevice::createServer();
    pServer->setCallbacks(new ServerCallbacks(this));

    NimBLEService* svc = pServer->createService(BLE_SERVICE_UUID);

    pSsidChar = svc->createCharacteristic(BLE_SSID_CHAR_UUID,
                    NIMBLE_PROPERTY::WRITE);
    pSsidChar->setCallbacks(new SsidCallback(this));

    pPassChar = svc->createCharacteristic(BLE_PASS_CHAR_UUID,
                    NIMBLE_PROPERTY::WRITE);
    pPassChar->setCallbacks(new PassCallback(this));

    // NimBLE adds CCCD automatically for NOTIFY characteristics
    pStatusChar = svc->createCharacteristic(BLE_STATUS_CHAR_UUID,
                      NIMBLE_PROPERTY::NOTIFY);

    svc->start();
    NimBLEDevice::getAdvertising()->addServiceUUID(BLE_SERVICE_UUID);
    NimBLEDevice::getAdvertising()->setScanResponse(true);
  }

  // -----------------------------------------------------------------------
  // Start advertising. Only called from setup() in BLE mode.
  // -----------------------------------------------------------------------
  void startBLEAdvertising() {
    setCoexMode(ESP_COEX_PREFER_BT);
    NimBLEDevice::getAdvertising()->start();
    state = State::BLE_ADVERTISING;
    DEBUG_PRINTLN(F("[BLE_OB] advertising started"));
    notifyStatus(STATUS_READY);
  }

  // -----------------------------------------------------------------------
  // Begin a Wi-Fi connection attempt using provided credentials.
  // Switches to PREFER_BALANCE so BLE stays alive for result notification.
  // -----------------------------------------------------------------------
  void beginWifiAttempt() {
    DEBUG_PRINTF("[BLE_OB] Wi-Fi attempt #%d SSID: %s\n", retryCount + 1, pendingSsid);
    setCoexMode(ESP_COEX_PREFER_BALANCE);
    notifyStatus(STATUS_CONNECTING);
    WiFi.disconnect(true);
    WiFi.begin(pendingSsid, pendingPass);
    wifiAttemptStart = millis();
    state = State::WIFI_ATTEMPTING;
  }

  // -----------------------------------------------------------------------
  // Poll Wi-Fi status each runProvisioningLoop() iteration.
  // On success: saves credentials to LittleFS and signals WIFI_CONNECTED.
  // On failure: notifies the app and retries up to MAX_RETRIES times.
  // -----------------------------------------------------------------------
  void pollWifiAttempt() {
    wl_status_t wst      = WiFi.status();
    bool        timedOut = (millis() - wifiAttemptStart) > WIFI_ATTEMPT_TIMEOUT_MS;

    if (wst == WL_CONNECTED) {
      DEBUG_PRINTF("[BLE_OB] connected, IP: %s — saving and restarting\n",
                   WiFi.localIP().toString().c_str());
      // Boost BLE to deliver CONNECTED notification before restarting
      setCoexMode(ESP_COEX_PREFER_BT);
      notifyStatus(STATUS_CONNECTED);

      // Persist credentials so normal WLED mode picks them up after reboot.
      // serializeConfigToFS() is synchronous — the write is complete before
      // runProvisioningLoop() returns and ESP.restart() is called.
      strlcpy(multiWiFi[0].clientSSID, pendingSsid, 33);
      strlcpy(multiWiFi[0].clientPass, pendingPass, 65);
      serializeConfigToFS(); // synchronous LittleFS write

      state = State::WIFI_CONNECTED;
      return; // runProvisioningLoop() detects WIFI_CONNECTED and returns
    }

    bool noAP     = (wst == WL_NO_SSID_AVAIL);
    bool connFail = (wst == WL_CONNECT_FAILED);

    if (noAP || connFail || timedOut) {
      DEBUG_PRINTF("[BLE_OB] failed: status=%d noAP=%d connFail=%d timedOut=%d\n",
                   (int)wst, (int)noAP, (int)connFail, (int)timedOut);
      WiFi.disconnect(true);
      setCoexMode(ESP_COEX_PREFER_BT);

      if      (noAP)     notifyStatus(STATUS_SSID_NOT_FOUND);
      else if (connFail) notifyStatus(STATUS_WRONG_PASSWORD);
      else               notifyStatus(STATUS_TIMEOUT);

      retryCount++;
      if (retryCount >= MAX_RETRIES) {
        DEBUG_PRINTLN(F("[BLE_OB] max retries — back to advertising"));
        retryCount = 0;
        state = State::BLE_ADVERTISING;
        NimBLEDevice::getAdvertising()->start();
      } else {
        DEBUG_PRINTF("[BLE_OB] retry %d in %d ms\n", retryCount, retryDelays[retryCount]);
        nextRetryAt = millis() + retryDelays[retryCount];
        state = State::FAILED;
      }
    }
  }

  // -----------------------------------------------------------------------
  // Blocking provisioning loop — called from setup() in BLE mode.
  //
  // By blocking here we prevent WLED's setup() from proceeding to
  // initServer() and initIR(). Both of those install interrupt handlers
  // that conflict with the BT controller's high-priority interrupt handler
  // (hli_c_handler, hli_api.c:107) and cause an IllegalInstruction panic.
  //
  // NimBLE runs in its own FreeRTOS tasks and is unaffected by the main
  // Arduino task being blocked here. delay() keeps the FreeRTOS scheduler
  // active and resets the task watchdog.
  // -----------------------------------------------------------------------
  void runProvisioningLoop() {
    for (;;) {
      switch (state) {
        case State::BLE_ADVERTISING:
          if (credentialsReceived) {
            credentialsReceived = false;
            retryCount = 0;
            beginWifiAttempt();
          }
          break;
        case State::WIFI_ATTEMPTING:
          pollWifiAttempt();
          break;
        case State::FAILED:
          if (millis() >= nextRetryAt) beginWifiAttempt();
          break;
        case State::WIFI_CONNECTED:
          return; // provisioning done; caller will ESP.restart()
        default:
          break;
      }
      delay(100); // yield to FreeRTOS; lets NimBLE tasks and WiFi run
    }
  }

  // -----------------------------------------------------------------------
  // BLE server-level callbacks.
  // Re-starts advertising when the app disconnects so the user can retry.
  // -----------------------------------------------------------------------
  class ServerCallbacks : public NimBLEServerCallbacks {
    BLEOnboardingUsermod* p;
  public:
    explicit ServerCallbacks(BLEOnboardingUsermod* parent) : p(parent) {}
    void onConnect(NimBLEServer*) override {
      DEBUG_PRINTLN(F("[BLE_OB] client connected"));
    }
    void onDisconnect(NimBLEServer*) override {
      DEBUG_PRINTLN(F("[BLE_OB] client disconnected"));
      if (p->state == State::BLE_ADVERTISING || p->state == State::FAILED) {
        DEBUG_PRINTLN(F("[BLE_OB] re-advertising after client drop"));
        NimBLEDevice::getAdvertising()->start();
      }
    }
  };

  class SsidCallback : public NimBLECharacteristicCallbacks {
    BLEOnboardingUsermod* p;
  public:
    explicit SsidCallback(BLEOnboardingUsermod* parent) : p(parent) {}
    void onWrite(NimBLECharacteristic* c) override {
      strlcpy(p->pendingSsid, c->getValue().c_str(), sizeof(p->pendingSsid));
      DEBUG_PRINTF("[BLE_OB] SSID written: %s\n", p->pendingSsid);
    }
  };

  class PassCallback : public NimBLECharacteristicCallbacks {
    BLEOnboardingUsermod* p;
  public:
    explicit PassCallback(BLEOnboardingUsermod* parent) : p(parent) {}
    void onWrite(NimBLECharacteristic* c) override {
      strlcpy(p->pendingPass, c->getValue().c_str(), sizeof(p->pendingPass));
      DEBUG_PRINTLN(F("[BLE_OB] password written"));
      if (strlen(p->pendingSsid) > 0) {
        DEBUG_PRINTLN(F("[BLE_OB] credentials complete, triggering attempt"));
        p->credentialsReceived = true;
      }
    }
  };

public:
  // -----------------------------------------------------------------------
  // setup(): determine boot mode.
  //
  // No credentials → BLE provisioning mode.
  //   Mirrors WLED's own network.cpp check: DEFAULT_CLIENT_SSID ("Your_Network")
  //   is the compile-time default present even when no config exists.
  //
  // Credentials present → normal WLED mode, BLE stack never initialised.
  // -----------------------------------------------------------------------
  void setup() override {
    // Mirror WLED network.cpp logic: "Your_Network" (DEFAULT_CLIENT_SSID) means
    // no user-configured credential exists even though the field is non-empty.
    bool hasCredentials = multiWiFi.size() > 1 ||
                          (strlen(multiWiFi[0].clientSSID) >= 1 &&
                           strcmp_P(multiWiFi[0].clientSSID, PSTR(DEFAULT_CLIENT_SSID)) != 0);
    DEBUG_PRINTF("[BLE_OB] setup: hasCredentials=%d ssid='%s'\n",
                 (int)hasCredentials, multiWiFi[0].clientSSID);

    if (!hasCredentials) {
      bleMode = true;
      initBLE();
      startBLEAdvertising();
      // Block here so WLED never reaches initServer()/initIR().
      // Those interrupt handlers crash with the BT controller's HLI.
      runProvisioningLoop();
      // serializeConfigToFS() was already called inside pollWifiAttempt().
      // Give LittleFS a moment to settle, then hard-reset into normal WLED mode.
      delay(300);
      ESP.restart();
      return; // unreachable
    }
    // Credentials exist: bleMode=false, BLE stack never initialised.
  }

  // -----------------------------------------------------------------------
  // loop(): no-op in normal WLED mode (bleMode=false).
  //
  // In BLE mode, setup() blocks inside runProvisioningLoop() and never
  // returns, so loop() is never reached for that boot. The state machine
  // runs entirely inside runProvisioningLoop().
  //
  // NOTE: To re-provision, use the WLED web UI (Security → Factory reset)
  // or clear /cfg.json via the LittleFS editor. On next boot this mod
  // will detect no credentials and enter BLE mode.
  // -----------------------------------------------------------------------
  void loop() override {
    // BLE mode: setup() never returns, so this is unreachable.
    // Normal mode: nothing to do.
  }

  uint16_t getId() override { return USERMOD_ID_BLE_ONBOARDING; }
};

static BLEOnboardingUsermod ble_onboarding;
REGISTER_USERMOD(ble_onboarding);

#endif // ARDUINO_ARCH_ESP32
